//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorgenCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class avcms_wallpapers
    {
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string file { get; set; }
        public Nullable<long> category_id { get; set; }
        public Nullable<long> date_added { get; set; }
        public Nullable<long> date_edited { get; set; }
        public Nullable<long> creator_id { get; set; }
        public Nullable<long> editor_id { get; set; }
        public Nullable<bool> published { get; set; }
        public Nullable<long> publish_date { get; set; }
        public int featured { get; set; }
        public string slug { get; set; }
        public long hits { get; set; }
        public long last_hit { get; set; }
        public string resize_type { get; set; }
        public string crop_position { get; set; }
        public long total_downloads { get; set; }
        public long last_download { get; set; }
        public long comments { get; set; }
        public long original_width { get; set; }
        public long original_height { get; set; }
        public long likes { get; set; }
        public long dislikes { get; set; }
        public Nullable<int> submitter_id { get; set; }
    }
}
