//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorgenCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class avcms_tag_taxonomy
    {
        public int content_id { get; set; }
        public int taxonomy_id { get; set; }
        public string content_type { get; set; }
    }
}
