//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorgenCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class avcms_wallpaper_categories
    {
        public long id { get; set; }
        public string name { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<int> parent { get; set; }
        public string slug { get; set; }
        public string description { get; set; }
        public string parents { get; set; }
        public string children { get; set; }
    }
}
