//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorgenCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class avcms_hits
    {
        public long id { get; set; }
        public string type { get; set; }
        public Nullable<int> content_id { get; set; }
        public Nullable<int> date { get; set; }
        public string ip { get; set; }
        public string column { get; set; }
    }
}
