//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoorgenCore.Models
{
    using Helpers;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class wssEntities : DbContext
    {
        public wssEntities()
            //: base("name=wssEntities")
            : base(ConnectionStringBuildHelper.Construct())
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<avcms_tags> avcms_tags { get; set; }
        public virtual DbSet<avcms_wallpaper_categories> avcms_wallpaper_categories { get; set; }
        public virtual DbSet<avcms_wallpapers> avcms_wallpapers { get; set; }
        public virtual DbSet<avcms_tag_taxonomy> avcms_tag_taxonomy { get; set; }
    }
}
